### ISSUE TITLE
PDF generation

### ISSUE THREAD

**Issue by MelvinNau** [davidjuhyung/puppeteer-api#1]
Hi ! 

I'm dealding with some problem as you! Your api is a good point, and an answer to a need, thanks

On my side, I use Puppeteer to generate dynamic pdf's, so I have to send it a variable at some point for build the html

Is this something you're going to look into by any chance? 

Thanks a lot

**Comment by davidjuhyung** [comment]
Yeah I can generate the dynamic pdf too, as that is provided by Puppeteer. Anything that can be achieved in Puppeteer can be achieved through this API, except I haven't built one yet. I will try to make one in the near future, but feel free to make a PR if you need it badly.

**Comment by davidjuhyung** [comment]
I have added PDF generation from HTML, let me know if that is what you are looking for.
